# fly.toml app configuration file generated for pizzaz-mcp on 2025-10-10T15:54:49+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pizzaz-mcp'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/mcp'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
