name: pizzaz-mcp-server
region: nyc

services:
  - name: web
    github:
      repo: MarkMYond/pizzaz
      branch: main
      deploy_on_push: true
    
    dockerfile_path: Dockerfile
    
    http_port: 8000
    
    envs:
      - key: BASE_URL
        scope: RUN_TIME
        value: ${APP_URL}
    
    instance_count: 1
    instance_size_slug: basic-xxs
    
    # Health check disabled as HEAD requests not fully implemented
    # Server responds to GET requests successfully
    
    routes:
      - path: /
